# docker-compose.yml
version: '2'

services:
  
  database:
    image: ivanjatz/aass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 60s
      retries: 10

  camunda_cockpit:
    build:  
      context: ./camunda_cockpit/.
    # image: ivanjatz/camunda-cockpit
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  filter_microservice:
    build:  
      context: ../aass_project_train_be/microservices/filter_microservice/.
    #image: ivanjatz/filter-microservice
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy

  price_microservice:
    #image: ivanjatz/price-calculator-microservice
    build: 
      context: ../aass_project_train_be/microservices/price_calculation_microservice/.
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy

  ticket_microservice:
    #image: ivanjatz/ticket-microservice
    build:  
      context: ../aass_project_train_be/microservices/ticket_microservice/.
    ports:
      - "8003:8000"
    environment:
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy

  notification_microservice:
    #image: ivanjatz/notification-microservice
    build:  
      context: ../aass_project_train_be/microservices/notification_microservice/.
    ports:
      - "8004:8000"
    environment:
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy

  web:
    build:  
      context: ../aass-project-train/aass-project-train-fe/fe-camunda/.
    ports:
      - "8081:8080"
    environment:
      - PRICE_HOST=price_microservice
      - PRICE_PORT=8000
      - TICKET_HOST=ticket_microservice
      - TICKET_PORT=8000
      - FILTER_HOST=filter_microservice
      - FILTER_PORT=8000
    depends_on:
      database:
        condition: service_healthy

  camunda_controller:
    build: .
    #image: ivanjatz/camunda-controller
    environment:
      - PRICE_HOST=price_microservice
      - PRICE_PORT=8000
      - TICKET_HOST=ticket_microservice
      - TICKET_PORT=8000
      - FILTER_HOST=filter_microservice
      - FILTER_PORT=8000
      - NOTIFICATION_HOST=notification_microservice
      - NOTIFICATION_PORT=8000
      - CAMUNDA_HOST=camunda_cockpit
      - CAMUNDA_PORT=8080
    depends_on:
      - ticket_microservice
      - price_microservice
      - filter_microservice
      - notification_microservice
      - camunda_cockpit


